/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://aceshl3krjg4rgtaxctab6f6je.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gm3zpf2pmzcb5ojdeefhcxams4",
    "aws_cognito_identity_pool_id": "us-east-2:05e08bed-fdf8-4dd2-a6e7-91a555c9624c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_K9j07gSlL",
    "aws_user_pools_web_client_id": "1duegb4ijtb9drcm1i2q20t81t",
    "oauth": {}
};


export default awsmobile;
